<a href="https://colab.research.google.com/github/noorehira/ProgrammingForAI/blob/main/Lab_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Quiz-2**

In [1]:
import numpy as np
import pandas as pd

In [2]:
temp_df = pd.read_csv('/content/reviews_dataset.csv')

In [3]:
temp_df.shape

(2225, 2)

In [10]:
df = temp_df.iloc[:5000]

In [11]:
df.shape

(2225, 2)

In [12]:
df.head()

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [13]:
df['news'][1]

'Oil rebounds from weather effect\n \n Oil prices recovered in Asian trade on Tuesday, after falling in New York on milder winter weather across the US.\n \n With winter temperatures staying relatively high in the northern US, a barrel of light crude ended Monday down $1.33 to $42.12. However crude prices have rebounded in Asia, rising to $42.30 a barrel for February delivery. In London, trading of Brent crude was suspended for a public holiday, but the price fell to $39.20 in the Far East.\n \n With milder temperatures expected to continue in the northern parts of the US over the next few days at least, analysts have said the price of oil may fall further - even if the decline was only temporary. "Weather has been the Achilles\' heel of this market," said ABN AMRO analyst John Brady. "But it is winter in the northeast. Eventually we\'ll get another cold blast." Despite a fall of more than $12 a barrel from the record highs reached in late October, the price of crude oil remains almost

# Drop words if not alphabets.
# Tokenize the sentence.
# Perform lemitization.

In [23]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Download the necessary NLTK resources
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

def drop_non_alphabets(text):
    """Drops words if not alphabets."""

    if isinstance(text, str):
        words = text.split()
        cleaned_words = [word for word in words if word.isalpha()]
        return ' '.join(cleaned_words)

    elif isinstance(text, list):
        text_str = ' '.join(text)  # Join list elements into a single string
        words = text_str.split()
        cleaned_words = [word for word in words if word.isalpha()]
        return ' '.join(cleaned_words)
    else:
        return text
df['news'] = df['news'].apply(drop_non_alphabets)

def tokenize_sentence(text):
    """Tokenizes the sentence."""
    tokens = word_tokenize(text)
    return tokens

def lemmatize_text(text):
    """Performs lemmatization."""
    # Ensure the input is a string
    if not isinstance(text, str):
        text = str(text)  # Convert to string if not already

    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(text)
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return ' '.join(lemmatized_tokens)

df['news'] = df['news'].apply(drop_non_alphabets)
df['news'] = df['news'].astype(str).apply(tokenize_sentence)

df['news'] = df['news'].apply(lemmatize_text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [24]:
print(df['news'][0])  # Print the first row of the 'news' column
print(df['news'][1])  # Print the second row of the 'news' column
# ... and so on

[ 'China ' , 'had ' , 'role ' , 'in ' , 'Yukos ' , 'China ' , 'lent ' , 'Russia ' , 'to ' , 'help ' , 'the ' , 'Russian ' , 'government ' , 'renationalise ' , 'the ' , 'key ' , 'Yuganskneftegas ' , 'unit ' , 'of ' , 'oil ' , 'group ' , 'it ' , 'has ' , 'been ' , 'The ' , 'Kremlin ' , 'said ' , 'on ' , 'Tuesday ' , 'that ' , 'the ' , 'which ' , 'Russian ' , 'state ' , 'bank ' , 'VEB ' , 'lent ' , 'Rosneft ' , 'to ' , 'help ' , 'buy ' , 'Yugansk ' , 'in ' , 'turn ' , 'came ' , 'from ' , 'Chinese ' , 'The ' , 'revelation ' , 'came ' , 'as ' , 'the ' , 'Russian ' , 'government ' , 'said ' , 'Rosneft ' , 'had ' , 'signed ' , ' a ' , 'oil ' , 'supply ' , 'deal ' , 'with ' , 'The ' , 'deal ' , 'sees ' , 'Rosneft ' , 'receive ' , 'in ' , 'credits ' , 'from ' , 'According ' , 'to ' , 'Russian ' , 'newspaper ' , 'these ' , 'credits ' , 'would ' , 'be ' , 'used ' , 'to ' , 'pay ' , 'off ' , 'the ' , 'loans ' , 'Rosneft ' , 'received ' , 'to ' , 'finance ' , 'the ' , 'purchase ' , 'of ' , 'Reports

# Vectorize using bigram and trigram techniques.

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

def vectorize_text(text):
    """Vectorizes the text using bigram and trigram techniques."""
    vectorizer = CountVectorizer(ngram_range=(2, 3))  # Consider bigrams and trigrams
    vectorized_text = vectorizer.fit_transform(text)
    return vectorized_text, vectorizer

X, vectorizer = vectorize_text(df['news'])

In [28]:

print(X.shape)
print(vectorizer.get_feature_names_out()[:20])

(2225, 784844)
['aa motoring' 'aa motoring trust' 'aaa and' 'aaa and second'
 'aaa battery' 'aaa battery is' 'aaa champion' 'aaa champion diane'
 'aaa indoor' 'aaa indoor and' 'aaa title' 'aaa title in' 'aaas am'
 'aaas am quite' 'aaas association' 'aaas association for' 'aaas champion'
 'aaas champion allyn' 'aaas champion kim' 'aaas indoor']


# Apply Random Forest algorithm with 150 trees.

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer


X = df['news']
y = df['type']


vectorizer = CountVectorizer(ngram_range=(2, 3))  # Consider bigrams and trigrams

X = vectorizer.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


rf_classifier = RandomForestClassifier(n_estimators=150, random_state=42)
rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)




# Evaluate overall accuracy of the model and class-wise precision / classification report
.

In [34]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

Accuracy: 0.8449438202247191
Confusion Matrix:
[[107   0   2   5   1]
 [  8  40   0  23   1]
 [  3   0  64   8   1]
 [  0   0   0 102   0]
 [ 12   1   0   4  63]]
Classification Report:
               precision    recall  f1-score   support

     business       0.82      0.93      0.87       115
entertainment       0.98      0.56      0.71        72
     politics       0.97      0.84      0.90        76
        sport       0.72      1.00      0.84       102
         tech       0.95      0.79      0.86        80

     accuracy                           0.84       445
    macro avg       0.89      0.82      0.84       445
 weighted avg       0.87      0.84      0.84       445



Perform following tasks on the provided Reviews Dataset.
* Drop words if not alphabets.
* Tokenize the sentence.
* Perform lemitization.
* Vectorize using bigram and trigram techniques.
* Apply Random Forest algorithm with 150 trees.
* Evaluate overall accuracy of the model and class-wise precision .