<a href="https://colab.research.google.com/github/noorehira/ProgrammingForAI/blob/main/pai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Generate a random matrix
random_matrix = np.random.rand(5, 5)

# Print the matrix
print("Random Matrix:")
print(random_matrix)


Random Matrix:
[[0.95680034 0.62797154 0.17597557 0.08508837 0.88501306]
 [0.69780759 0.77744771 0.16674481 0.27137157 0.90081642]
 [0.29647369 0.15863492 0.42744603 0.77616745 0.23239218]
 [0.12262065 0.20152643 0.64074702 0.38580824 0.05758121]
 [0.08420161 0.86498046 0.64163388 0.77227792 0.11869504]]
